# Generated by Django 2.2.2 on 2019-06-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripinorder',
            name='status',
        ),
    ]
