# Generated by Django 2.2.2 on 2019-06-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tripinorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Выполнен'), (4, 'Отменен')], default=1),
        ),
        migrations.AlterField(
            model_name='tripinorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Выполнен'), (4, 'Отменен')], default=1),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
